export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT   = "CREATE_PRODUCT"; // Nueva acción
export const GET_ALL_ORDERS   = "GET_ALL_ORDERS";
export const CREATE_ORDER     = "CREATE_ORDER";
export const REMOVE_ORDER     = "REMOVE_ORDER";
export const SUBTRACT_IN_ORDER      = "SUBTRACT_IN_ORDER ";
export const LOGIN_SUCCESS    = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS   = "LOGOUT_SUCCESS";
export const GET_BUYS   = "GET_BUYS";
